export const SAVE_FB_CREDENTIALS_START = "SAVE_FB_CREDENTIALS_START"
export const SAVE_FB_CREDENTIALS_SUCCESS = "SAVE_FB_CREDENTIALS_SUCCESS"
export const SAVE_FB_CREDENTIALS_FAIL = "SAVE_FB_CREDENTIALS_FAIL"